"use client";

export default function TermsPage() {
  return (
    <div className="flex flex-col min-h-screen" style={{ background: "var(--bg-base)", color: "var(--text-primary)" }}>
      <nav className="sticky top-0 z-50" style={{ background: "#f7f3ec", borderBottom: "1px solid #ddd5c8" }}>
        <div className="max-w-7xl mx-auto px-8 py-4 flex items-center justify-between">
          <a href="/" className="flex items-center gap-3">
            <div className="w-7 h-7 flex items-center justify-center" style={{ border: "1px solid #1c1a17" }}>
              <span className="text-[10px] font-bold tracking-tight" style={{ color: "#1c1a17" }}>CB</span>
            </div>
            <span className="text-sm font-medium tracking-widest uppercase" style={{ color: "#1c1a17", letterSpacing: "0.12em" }}>CodeBrief</span>
          </a>
        </div>
      </nav>
      <main className="flex-1">
        <section style={{ background: "#111111" }}>
          <div className="max-w-3xl mx-auto px-8 py-14">
            <p className="section-label mb-4" style={{ color: "rgba(245,242,238,0.4)" }}>Legal</p>
            <h1 className="text-4xl font-light tracking-tight" style={{ color: "#f5f2ee", letterSpacing: "-0.02em", fontFamily: "var(--font-serif-display), Georgia, serif", fontWeight: 400 }}>Terms of Service</h1>
            <p className="text-sm mt-3" style={{ color: "rgba(245,242,238,0.4)", fontWeight: 300 }}>Last updated: January 1, 2025</p>
          </div>
        </section>
        <section style={{ background: "#ffffff" }}>
          <div className="max-w-3xl mx-auto px-8 py-12 space-y-8">
            {[
              { title: "Acceptance of Terms", body: "By accessing or using CodeBrief, you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use CodeBrief." },
              { title: "Description of Service", body: "CodeBrief is an AI-powered research tool that generates building code analysis reports based on project parameters provided by the user. Reports are generated using publicly available code data and AI language models. CodeBrief is a research aid, not a licensed professional service." },
              { title: "No Professional Advice", body: "Reports generated by CodeBrief do not constitute legal, architectural, engineering, or professional advice. Building codes are life-safety regulations. All information provided by CodeBrief must be independently verified with the Authority Having Jurisdiction (AHJ) before being relied upon for design, permitting, or construction decisions. CodeBrief expressly disclaims any liability for decisions made based on its reports without independent professional verification." },
              { title: "User Accounts", body: "You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You must notify us immediately of any unauthorized use of your account." },
              { title: "Acceptable Use", body: "You agree not to use CodeBrief to: (a) violate any applicable law or regulation; (b) submit false or misleading project parameters; (c) attempt to reverse-engineer, scrape, or extract data from the service in bulk; (d) resell or redistribute CodeBrief reports without attribution." },
              { title: "Payment and Billing", body: "Paid plans are billed monthly or annually in advance. All fees are non-refundable except as required by law. We reserve the right to change pricing with 30 days notice. Continued use after a price change constitutes acceptance of the new pricing." },
              { title: "Limitation of Liability", body: "To the maximum extent permitted by law, CodeBrief and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the service, including any reliance on generated reports for design, permitting, or construction decisions." },
              { title: "Changes to Terms", body: "We may update these terms from time to time. We will notify you of material changes by email or by posting a notice on the service. Continued use after changes constitutes acceptance." },
              { title: "Contact", body: "For questions about these terms, contact us at legal@codebrief.ai." },
            ].map((section) => (
              <div key={section.title} className="pb-8" style={{ borderBottom: "1px solid var(--border-light)" }}>
                <h2 className="text-base font-medium mb-3" style={{ color: "var(--text-primary)" }}>{section.title}</h2>
                <p className="text-sm leading-relaxed" style={{ color: "var(--text-secondary)", fontWeight: 300 }}>{section.body}</p>
              </div>
            ))}
          </div>
        </section>
      </main>
      <footer style={{ background: "var(--bg-warm)", borderTop: "1px solid var(--border-light)" }}>
        <div className="max-w-7xl mx-auto px-8 py-6 flex items-center justify-between">
          <span className="text-[11px]" style={{ color: "var(--text-muted)" }}>&copy; {new Date().getFullYear()} CodeBrief</span>
          <div className="flex items-center gap-6">
            {([["/", "Home"], ["/privacy", "Privacy"], ["/terms", "Terms"]] as [string, string][]).map(([href, label]) => (
              <a key={label} href={href} className="text-[11px]" style={{ color: "var(--text-muted)" }}>{label}</a>
            ))}
          </div>
        </div>
      </footer>
    </div>
  );
}
